### ISSUE TITLE
Game is now freezing for too long after play presses start

### ISSUE THREAD

**Issue by itravers** [itravers/ARaceInSpace#8]
Player presses the start button and everything freezes, as if it is having trouble loading.

**Comment by itravers** [comment]
I thought this was just a problem with my tablet, but now it's happening with the emulator too.
It's not just the start screen, but it seems to be ALL screen transitions.
Why is this happening, when there was no change in the code?????

**Comment by itravers** [comment]
Got rid of admob ad controller and it's not making a difference, so that's not the problem at least.

**Comment by itravers** [comment]
Tried commit 10dd7486ae177f650d704cc2d3de0366328a1726 which was before I solved issue #4 (where this previously was NOT happening and it was STILL happening.  Code confirmed to do something is now doing something else without being changed itself.

Suspects:
Something in a library changed.
Something in my build system changed

**Comment by itravers** [comment]
In commit 72b24e8fd51b0b9d38c4b3a21fef0bc282cf503b seeing error when I wasn't before: - : W/art: Attempt to remove non-JNI local reference, dumping thread

**Comment by itravers** [comment]
Issue occurs between these messages. Looks like it's stopping because a rest response isn't being delivered.

httpManger: send request to: http://192.168.1.197:3001/leaderboards/levelleaders
03-23 18:18:10.974 18386-18729/com.araceinspace.isaac.game I/System.out: Request Failed

Problem is originating client side from getLevelLeaders() not returning right away.

**Comment by itravers** [comment]
Looks like mongo wasn't running correctly on the backend. Tried logging into it, no connection, restarted.
now we are getting the following after the requestion to /levelleaders

03-23 18:28:22.330 28577-28606/com.araceinspace.isaac.game E/AndroidRuntime: FATAL EXCEPTION: GLThread 206
                                                                             Process: com.araceinspace.isaac.game, PID: 28577
                                                                             java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
                                                                                 at java.util.ArrayList.get(ArrayList.java:411)
                                                                                 at com.araceinspace.Screens.LEVELSELECTScreen.setupPortraitGUI(LEVELSELECTScreen.java:384)
                                                                                 at com.araceinspace.Screens.LEVELSELECTScreen.setup(LEVELSELECTScreen.java:111)
                                                                                 at com.araceinspace.Screens.Screen.<init>(Screen.java:52)
                                                                                 at com.araceinspace.Screens.LEVELSELECTScreen.<init>(LEVELSELECTScreen.java:0)
                                                                                 at com.araceinspace.Managers.RenderManager.loadScreen(RenderManager.java:98)
                                                                                 at com.araceinspace.Managers.GameStateManager.setCurrentState(GameStateManager.java:57)
                                                                                 at com.araceinspace.Screens.TITLEScreen$1.clicked(TITLEScreen.java:100)
                                                                                 at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:89)
                                                                                 at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:58)
                                                                                 at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:353)
                                                                                 at com.badlogic.gdx.InputMultiplexer.touchUp(InputMultiplexer.java:96)
                                                                                 at com.badlogic.gdx.backends.android.AndroidInput.processEvents(AndroidInput.java:379)
                                                                                 at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:457)
                                                                                 at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1553)
                                                                                 at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1253)
03-23 18:28:26.335 28577-28577/com.araceinspace.isaac.game E/AndroidGraphics: waiting for pause synchronization took too long; assuming deadlock and killing

**Comment by itravers** [comment]
I'm convinced this has something to do with issue #6 
the db is corrupt because a 0 was inserted somewhere, so the client isn't seeing something about the level buttons.

**Comment by itravers** [comment]
mongo error topology was destroyed

**Comment by itravers** [comment]
The problem is the backend was spitting out errors into the input to the frontend. It was bypassing the httpManagers checking and was being parsed into leaderBoardChamps on the level select page.

When the page tried to display them all, we'd get a null pointer in an array. Fixed the backend and the problem is now gone.

Need to add a check into frontend so this doesn't need to happen.

**Comment by itravers** [comment]
Fixed with commit https://github.com/itravers/ARaceInSpace_backend/commit/e0391b8fefe1ce57c5362d1ee423939f301dbf77 in backend
and with commit 24744c0be27779084017e7c91a35ff7615282cb4 in frontend
